
name: 'Weekly Radar'
description: 'Keep your team in sync with a Weekly Radar'
author: 'imjohnbo'
inputs: 
  assignees:
    description: 'Space delimited list of Weekly Radar assignees'
    default: ''
  label:
    description: 'Label attached to your Weekly Radar'
    default: 'radar'
runs:
  using: 'node12'
  main: 'index.js'