name: 'Weekly Radar'
description: 'Keep your team in sync with a Weekly Radar'
author: 'imjohnbo'
branding:
  icon: 'activity'
  color: 'blue'
inputs:
  assignees:
    description: 'Space delimited list of Weekly Radar assignees'
    default: ''
    required: false
  label:
    description: 'Label attached to your Weekly Radar'
    default: 'radar'
    required: false
  pinned:
    description: 'Whether to pin your Weekly Radar and unpin the previous one'
    default: false
    required: false
outputs:
  issue_number:
    description: 'The issue number of the created radar issue'
runs:
  using: 'node12'
  main: 'dist/index.js'
