name: 'Scheduled Issue'
description: 'Automate your manual tasks with a scheduled issue'
author: 'imjohnbo'
branding:
  icon: 'activity'
  color: 'blue'
inputs:
  labels:
    description: 'Comma delimited list of issue labels. Required value either as input or in YAML header of issue template.'
    default: ''
    required: false
  title:
    description: 'Issue title. Required value either as input or in YAML header of issue template.'
    default: ''
    required: false
  assignees:
    description: 'Comma delimited list of issue assignees'
    default: ''
    required: false
  body:
    description: 'Issue body'
    default: ''
    required: false
  pinned:
    description: 'Whether to pin this issue and unpin the previous one'
    default: 'false'
    required: false
  close-previous:
    description: 'Whether to close the most recent previous issue with a matching label'
    default: 'false'
    required: false
  template:
    description: 'Path to template used in issue, eg. .github/ISSUE_TEMPLATE/bug_report.md'
    default: ''
    required: false
outputs:
  issue-number:
    description: 'The issue number of the created issue'
runs:
  using: 'node12'
  main: 'dist/index.js'
