
name: 'Weekly Radar'
description: 'Keep your team in sync with a Weekly Radar'
author: 'imjohnbo'
inputs: 
  assignees:
    description: 'Space delimited list of Weekly Radar assignees'
    default: ''
  patToken:
    description: 'Personal Access Token with issue write access'
runs:
  using: 'node12'
  main: 'index.js'